export const bookTypes = {
    SET_PAGE: 'SET_PAGE',
    SET_BOOK: 'SET_BOOK',
    SET_TOTAL_PAGE: 'SET_TOTAL_PAGE',
    SET_CATEGORY_BOOK: 'SET_CATEGORY_BOOK',
    SET_PUBLISHSER: 'SET_PUBLISHSER',
    SET_AUTHOR: 'SET_AUTHOR',
}