export const bookTypes = {
    SET_PAGE: 'SET_PAGE',
    SET_BOOK: 'SET_BOOK',
    SET_TOTAL_PAGE: 'SET_TOTAL_PAGE',
    SET_CATEGORY_BOOK: 'SET_CATEGORY_BOOK',
    SET_PUBLISHSER: 'SET_PUBLISHSER',
    SET_AUTHOR: 'SET_AUTHOR',
    ADD_CATEGORY_SUCCESS: 'ADD_CATEGORY_SUCCESS',
    ADD_CATEGORY_FAIL: 'ADD_CATEGORY_FAIL',
    UPDATE_CATEGORY_SUCCESS: 'UPDATE_CATEGORY_SUCCESS',
    UPDATE_CATEGORY_FAIL: 'UPDATE_CATEGORY_FAIL',
    RESET_CATEGORY: 'RESET_CATEGORY',
    ADD_AUTHOR_SUCCESS: 'ADD_AUTHOR_SUCCESS',
    ADD_AUTHOR_FAIL: 'ADD_AUTHOR_FAIL',
    UPDATE_AUTHOR_SUCCESS: 'UPDATE_AUTHOR_SUCCESS',
    UPDATE_AUTHOR_FAIL: 'UPDATE_AUTHOR_FAIL',
    RESET_AUTHOR: 'RESET_AUTHOR',
    ADD_PUBLISHER_SUCCESS: 'ADD_PUBLISHER_SUCCESS',
    ADD_PUBLISHER_FAIL: 'ADD_PUBLISHER_FAIL',
    UPDATE_PUBLISHER_SUCCESS: 'UPDATE_PUBLISHER_SUCCESS',
    UPDATE_PUBLISHER_FAIL: 'UPDATE_PUBLISHER_FAIL',
    RESET_PUBLISHER: 'RESET_PUBLISHER',
}

export const userTypes = {
    SET_USER: 'SET_USER'
}